services:
  - type: web
    name: ad-library-scraper
    env: node
    plan: starter
    buildCommand: npm install --production
    startCommand: node src/index-simple.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /api/health