services:
  - type: web
    name: ad-library-scraper
    env: node
    plan: starter
    buildCommand: bun install
    startCommand: bun start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /api/health