services:
  - type: web
    name: ad-library-scraper
    env: node
    plan: starter
    buildCommand: npm ci --only=production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_PATH
        value: ./data/ads.db
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
    healthCheckPath: /api/health