services:
  - type: web
    name: ad-library-scraper
    env: node
    plan: starter
    buildCommand: |
      # Update package list
      apt-get update
      
      # Install Chrome directly from Google
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
      apt-get update
      
      # Install Chrome and required dependencies
      apt-get install -y google-chrome-stable
      
      # Verify Chrome installation
      google-chrome --version || echo "Chrome installation failed"
      which google-chrome-stable || echo "Chrome not found in PATH"
      ls -la /usr/bin/google-chrome* || echo "No Chrome binaries found"
      
      # Install Node dependencies
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
    healthCheckPath: /api/health