services:
  - type: web
    name: ad-library-scraper
    env: node
    plan: starter
    buildCommand: |
      apt-get update && apt-get install -y wget gnupg ca-certificates
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      apt-get update && apt-get install -y google-chrome-stable
      npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CHROME_EXECUTABLE_PATH
        value: /usr/bin/google-chrome
    healthCheckPath: /api/health