services:
  - type: web
    name: ad-library-scraper
    env: node
    plan: starter
    buildCommand: |
      echo "=== Installing Node dependencies ==="
      npm install
      
      echo "=== Skipping browser installation - using external browser services ==="
      echo "Fallback strategy: Playwright (if available) -> Browserless.io -> Local Puppeteer"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: BROWSERLESS_TOKEN
        value: ""
    healthCheckPath: /api/health